### ISSUE TITLE
Doesn't install.

### ISSUE THREAD

**Issue by YarharALC** [dapetcu21/atom-autocomplete-lua#22]
```
npm ERR! git clone C:\Users\Dylan\.atom\.apm\_git-remotes\git-github-com-dapetcu21-luaparse-git-1df252af C:\Users\Dylan\AppData\Local\Temp\npm-3700-e9f353da\git-cache-3f5af6ef\5a1fd2868adecb79f6bc57ee1f1880a3ea83ad8b: Cloning into 'C:\Users\Dylan\AppData\Local\Temp\npm-3700-e9f353da\git-cache-3f5af6ef\5a1fd2868adecb79f6bc57ee1f1880a3ea83ad8b'...
npm ERR! git clone C:\Users\Dylan\.atom\.apm\_git-remotes\git-github-com-dapetcu21-luaparse-git-1df252af C:\Users\Dylan\AppData\Local\Temp\npm-3700-e9f353da\git-cache-3f5af6ef\5a1fd2868adecb79f6bc57ee1f1880a3ea83ad8b: error: cannot spawn sh: No such file or directory
npm ERR! git clone C:\Users\Dylan\.atom\.apm\_git-remotes\git-github-com-dapetcu21-luaparse-git-1df252af C:\Users\Dylan\AppData\Local\Temp\npm-3700-e9f353da\git-cache-3f5af6ef\5a1fd2868adecb79f6bc57ee1f1880a3ea83ad8b: fatal: unable to fork
npm ERR! git clone C:\Users\Dylan\.atom\.apm\_git-remotes\git-github-com-dapetcu21-luaparse-git-1df252af C:\Users\Dylan\AppData\Local\Temp\npm-3700-e9f353da\git-cache-3f5af6ef\5a1fd2868adecb79f6bc57ee1f1880a3ea83ad8b: 
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit  dapetcu21/luaparse resetting remote C:\Users\Dylan\.atom\.apm\_git-remotes\git-https-github-com-dapetcu21-luaparse-git-7c30d46c because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\Dylan\.atom\.apm\_git-remotes\_templates --mirror https://github.com/dapetcu21/luaparse.git C:\Users\Dylan\.atom\.apm\_git-remotes\git-https-github-com-dapetcu21-luaparse-git-7c30d46c: Cloning into bare repository 'C:\Users\Dylan\.atom\.apm\_git-remotes\git-https-github-com-dapetcu21-luaparse-git-7c30d46c'...
npm ERR! git clone --template=C:\Users\Dylan\.atom\.apm\_git-remotes\_templates --mirror https://github.com/dapetcu21/luaparse.git C:\Users\Dylan\.atom\.apm\_git-remotes\git-https-github-com-dapetcu21-luaparse-git-7c30d46c: fatal: Unable to find remote helper for 'https'
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit  dapetcu21/luaparse resetting remote C:\Users\Dylan\.atom\.apm\_git-remotes\git-github-com-dapetcu21-luaparse-git-b80768f9 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\Dylan\.atom\.apm\_git-remotes\_templates --mirror git@github.com:dapetcu21/luaparse.git C:\Users\Dylan\.atom\.apm\_git-remotes\git-github-com-dapetcu21-luaparse-git-b80768f9: Cloning into bare repository 'C:\Users\Dylan\.atom\.apm\_git-remotes\git-github-com-dapetcu21-luaparse-git-b80768f9'...
npm ERR! git clone --template=C:\Users\Dylan\.atom\.apm\_git-remotes\_templates --mirror git@github.com:dapetcu21/luaparse.git C:\Users\Dylan\.atom\.apm\_git-remotes\git-github-com-dapetcu21-luaparse-git-b80768f9: error: cannot spawn ssh: No such file or directory
npm ERR! git clone --template=C:\Users\Dylan\.atom\.apm\_git-remotes\_templates --mirror git@github.com:dapetcu21/luaparse.git C:\Users\Dylan\.atom\.apm\_git-remotes\git-github-com-dapetcu21-luaparse-git-b80768f9: fatal: unable to fork
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\Dylan\\AppData\\Local\\atom\\app-1.18.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Dylan\\AppData\\Local\\atom\\app-1.18.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Dylan\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Dylan\\.atom\\.apmrc" "install" "C:\\Users\\Dylan\\AppData\\Local\\Temp\\d-11762-508-1s3fiq7.des4w8kt9\\package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style" "--msvs_version=2013"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\Dylan\.atom\.apm\_git-remotes\_templates --mirror git@github.com:dapetcu21/luaparse.git C:\Users\Dylan\.atom\.apm\_git-remotes\git-github-com-dapetcu21-luaparse-git-b80768f9
npm ERR! Cloning into bare repository 'C:\Users\Dylan\.atom\.apm\_git-remotes\git-github-com-dapetcu21-luaparse-git-b80768f9'...
npm ERR! error: cannot spawn ssh: No such file or directory
npm ERR! fatal: unable to fork
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by dapetcu21** [comment]
I think you need to have git installed on windows for APM to work with the lua-parse hosted on my github. This will get solved when I get a chance to make a PR for lua-parse that will get accepted and then pushed to npm.

**Comment by YarharALC** [comment]
I do have Git installed. That's a little kooky.

**Comment by dapetcu21** [comment]
Maybe open an issue at [atom/atom](https://github.com/atom/atom) about this?
